#!/bin/bash

isFile(){
        L=`cat $1|wc -l`
        n=$(($L - 150))
        if [ $n -gt 0 ];then
                sed -i "1,${n}d" $1
        fi
}

isDir(){
        echo $1
        for i in `ls $1`
        do
                if [ -f $1/$i ];then
                        isFile $1/$i
                else
                        isDir $1/$i
                fi
        done
}

isDir '/var/log'
